version: '3.7'

services:
  locust-master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./load-tests:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://raft-example-1:8080
  locust-worker:
      deploy:
        replicas: 6
      image: locustio/locust
      volumes:
        - ./load-tests:/mnt/locust
      command: -f /mnt/locust/locustfile.py --worker --master-host locust-master
  raft-example:
    image: raft-example
    hostname: "raft-example-{{.Task.Slot}}"
    ports:
      - "8080:8080"
    environment:
      node_id: "{{.Task.Slot}}"
      nodes: 3
      node_base_name: raft-example
      port: 8080
    deploy:
      replicas: 3
  prometheus:
    image: prom/prometheus
    volumes:
      - type: bind
        source: ./conf/prometheus.yml
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
