version: '3.7'
volumes:

  grafana_data: {}

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    command: --allow_dynamic_housekeeping=false --max_housekeeping_interval=10s --housekeeping_interval=1s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 128M
    ports:
      - 8083:8080
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  locust-exporter:
    image: containersol/locust_exporter
    container_name: locust-exporter
    environment:
      LOCUST_EXPORTER_URI: http://locust-master:8089
  locust-master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./load-tests:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://raft-example-1:8080
  locust-worker:
      deploy:
        replicas: 2
        resources:
          limits:
            cpus: '0.5'
            memory: 512M
          reservations:
            cpus: '0.5'
            memory: 128M
      image: locustio/locust
      volumes:
        - ./load-tests:/mnt/locust
      command: -f /mnt/locust/locustfile.py --worker --master-host locust-master

  raft-example:
    image: raft-example
    hostname: "raft-example-{{.Task.Slot}}"
    ports:
      - "8080:8080"
    environment:
      node_id: "{{.Task.Slot}}"
      nodes: 3
      node_base_name: raft-example
      port: 8080
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 128M
  prometheus:
    image: prom/prometheus
    volumes:
      - type: bind
        source: ./conf/prometheus.yml
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - DS_PROMETHEUS=Prometheus
    restart: unless-stopped

    ports:
      - 8085:3000
    labels:
      org.label-schema.group: "monitoring"
