{
 "title": "Consensus metrics",
 "description": "Consensus metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({__name__=~\"container.*\"},instance)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"$host\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{iinstance=~\"$host\",name=~\"$container\",name=~\".+\"}) > 0)",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=~\"$host\",name=~\"$container\",name=~\".+\"})"
    }
   ]
  },
  {
   "title": "Users",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "locust_users", "legendFormat": "Users" }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "locust_requests_num_requests{method=~\"\"}"
    }
   ]
  },
  {
   "title": "Operations on server",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_set_value[10s])) by (instance) * 60",
     "legendFormat": " set {{instance}}"
    },
    {
     "expr": "sum(rate(app_get_value[10s])) by (instance) * 60",
     "legendFormat": " get {{instance}}"
    }
   ]
  },
  {
   "title": "Fails on server",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_get_value_fail[10s])) by (instance) * 60",
     "legendFormat": " set {{instance}}"
    },
    {
     "expr": "sum(rate(app_get_value_fail[10s])) by (instance) * 60",
     "legendFormat": " get {{instance}}"
    }
   ]
  },
  {
   "title": "Get operation duration on server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_get_duration_seconds_bucket[5s])) by (le)) *100",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(app_get_duration_seconds_bucket[5s])) by (le)) *100",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(app_get_duration_seconds_bucket[5s])) by (le)) *100",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(app_get_duration_seconds_bucket[5s])) by (le)) *100",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Set operation duration on server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_set_duration_seconds_bucket[5s])) by (le)) *100",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(app_set_duration_seconds_bucket[5s])) by (le)) *100",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(app_set_duration_seconds_bucket[5s])) by (le)) *100",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(app_set_duration_seconds_bucket[5s])) by (le)) *100",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$host\",name=~\"$container\", name=~\".+\"}[10s])) by (name) *100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{instance=~\"$host\",name=~\"$container\",name=~\".+\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Network input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{instance=~\"$host\",name=~\"$container\",name=~\".+\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Network output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{instance=~\"$host\",name=~\"$container\",name=~\".+\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Cached Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (container_memory_cache{instance=~\"$host\",name=~\"$container\",name=~\".+\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "locust_users", "legendFormat": "Users" }
   ]
  },
  {
   "title": "Fails",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "locust_requests_fail_ratio" }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "locust_requests_num_requests{method=~\"\"}"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "locust_workers_count", "legendFormat": "Workers" }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(locust_requests_max_response_time)",
     "legendFormat": "AVG MAX"
    },
    {
     "expr": "avg(locust_requests_min_response_time)",
     "legendFormat": "AVG MIN"
    },
    {
     "expr": "avg(locust_requests_avg_response_time)",
     "legendFormat": "AVG AVG"
    },
    {
     "expr": "avg(locust_requests_median_response_time)",
     "legendFormat": "AVG MEDIAN"
    }
   ]
  },
  {
   "title": "Requests per endpoint / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(locust_requests_num_requests{method=~\".+\"}[1m])",
     "legendFormat": "{{ method}} - {{name}}"
    },
    {
     "expr": " sum(rate(locust_requests_num_requests{method=~\".+\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "locust_requests_fail_ratio * 100",
     "legendFormat": "fail_ratio [%]"
    }
   ]
  }
 ]
}